name: 'content_intelligence_pipeline'
version: '1.0.0'
config-version: 2

profile: 'content_intelligence_pipeline'

model-paths: ["models"]

models:
  content_intelligence_pipeline:
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
